// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaceXUkQW2Qk9Bi2r4rjT357EKKM2dsXE',
    appId: '1:840564024538:web:2dfc606e9f941f159071e3',
    messagingSenderId: '840564024538',
    projectId: 'hundred-days-beee0',
    authDomain: 'hundred-days-beee0.firebaseapp.com',
    storageBucket: 'hundred-days-beee0.appspot.com',
    measurementId: 'G-CZ6Q6H3VKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACPVp6NJTgk-STqr9RW2v9qaHv3J_g8E',
    appId: '1:840564024538:android:6997243c4a153ab09071e3',
    messagingSenderId: '840564024538',
    projectId: 'hundred-days-beee0',
    storageBucket: 'hundred-days-beee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDioQsdjTVx03mDm03FGH1KECVwoTcamic',
    appId: '1:840564024538:ios:cf26fc39efdea98e9071e3',
    messagingSenderId: '840564024538',
    projectId: 'hundred-days-beee0',
    storageBucket: 'hundred-days-beee0.appspot.com',
    iosBundleId: 'com.example.hundredDays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDioQsdjTVx03mDm03FGH1KECVwoTcamic',
    appId: '1:840564024538:ios:cf26fc39efdea98e9071e3',
    messagingSenderId: '840564024538',
    projectId: 'hundred-days-beee0',
    storageBucket: 'hundred-days-beee0.appspot.com',
    iosBundleId: 'com.example.hundredDays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaceXUkQW2Qk9Bi2r4rjT357EKKM2dsXE',
    appId: '1:840564024538:web:5fd53da4406b03d19071e3',
    messagingSenderId: '840564024538',
    projectId: 'hundred-days-beee0',
    authDomain: 'hundred-days-beee0.firebaseapp.com',
    storageBucket: 'hundred-days-beee0.appspot.com',
    measurementId: 'G-FQM2WCDRGG',
  );
}
